# it will give a name for github action
name: Node.js CI Testing

# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
      - name: Check code meets quality standards
        id: code-inspector
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_api_token: ${{ secrets.CODE_INSPECTOR_API_TOKEN }}
          force_ref: 'none'
          min_quality_grade: 'WARNING'
          min_quality_score: '50'
          max_defects_rate: '0.0001'
          max_complex_functions_rate: '0.0001'
          max_long_functions_rate: '0.0001'
          project_name: ''
          max_timeout_sec: '600'
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [check-quality]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: use node.js setting
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      # it will then install all dependencies
      - name: Install dependencies
        run: npm install
      # it will run alls unit-tests
      - name: Run all tests
        run: npm run test
      - name: Build api service
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 55ef7caf-1520-4ce3-8533-b0ab16f89454
          heroku_app_name: "test-onichan-api"
          heroku_email: delponleo@gmail.comst-onichan-api"
          heroku_email: delponleo@gmail.com